local colors_scheme = "killer-queen"

local function reload()
    for k, _ in pairs(package.loaded) do
        if k:match(colors_scheme) then
            package.loaded[k] = nil
        end
    end

    require(colors_scheme).setup()
    vim.cmd(("colorscheme %s"):format(colors_scheme))
end

vim.keymap.set(
    { "n" },
    "<leader>pr",
    reload,
    { silent = true, desc = "Reload plugin in debug mode" }
)

--[[
Comment = {},
Constant = {},
String = {},
Character = {},
Number = {},
Boolean = {},
Float = {},
Identifier = {},
Function = {},
Statement = {},
Conditional = {},
Repeat = {},
Label = {},
Operator = {},
Keyword = {},
Exception = {},
PreProc = {},
Include = {},
Define = {},
Macro = {},
PreCondit = {},
Type = {},
StorageClass = {},
Structure = {},
Typedef = {},
Special = {},
SpecialChar = {},
Tag = {},
Delimiter = {},
SpecialComment = {},
Debug = {},
Underlined = {},
Ignore = {},
Error = {},
Todo = {},

Conceal = {},
CurSearch = {},
Cursor = {},
lCursor = {},
CursorIM = {},
CursorColumn = {},
CursorLine = {},
Directory = {},
DiffAdd = {},
DiffChange = {},
DiffDelete = {},
DiffText = {},
EndOfBuffer = {},
TermCursor = {},
TermCursorNC = {},
ErrorMsg = {},
WinSeparator = {},
Folded = {},
FoldColumn = {},
SignColumn = {},
IncSearch = {},
Substitute = {},
LineNr = {},
LineNrAbove = {},
LineNrBelow = {},
CursorLineNr = {},
CursorLineFold = {},
CursorLineSign = {},
MatchParen = {},
ModeMsg = {},
MsgArea = {},
MsgSeparator = {},
MoreMsg = {},
NonText = {},
Normal = {},
NormalFloat = {},
FloatBorder = {},
FloatTitle = {},
FloatFooter = {},
NormalNC = {},
Pmenu = {},
PmenuSel = {},
PmenuKind = {},
PmenuKindSel = {},
PmenuExtra = {},
PmenuExtraSel = {},
PmenuSbar = {},
PmenuThumb = {},
Question = {},
QuickFixLine = {},
Search = {},
SpecialKey = {},
SpellBad = {},
SpellCap = {},
SpellLocal = {},
SpellRare = {},
StatusLine = {},
StatusLineNC = {},
TabLine = {},
TabLineFill = {},
TabLineSel = {},
Title = {},
Visual = {},
VisualNOS = {},
WarningMsg = {},
Whitespace = {},
WildMenu = {},
WinBar = {},
WinBarNC = {},
]]
